// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace gsDotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertaUsuario", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_alerta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime?>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_alerta");

                    b.Property<string>("Gravidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("gravidade");

                    b.Property<int>("IdEvento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_evento");

                    b.Property<int>("IdLocalizacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_localizacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdAlerta");

                    b.ToTable("alerta_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
